---
title: "XANES_Spectra_Merging"
author: "Morgan Barnes"
date: "2023-11-27"
output: html_document
---

##This code imports normalized xmu files that were exported from Athena and merges samples together based on eV
##Contact: Morgan E Barnes morgan.barnes@pnnl.gov

#### Set Up
```{r setup, include=FALSE, dev="CairoPNG"}
rm(list=ls(all=T))
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries
```{r library}
require(pacman)

pacman::p_load(tidyverse, purrr)

```

##### Confirm working directory:
```{r}
getwd()
```


##Samples
```{r}
#Load samples spectra and merge to make it easier to make a figure
file_names  <- c("BSLE_0013-solid_P-XANES.xmu.nor", "BSLE_0007-solid_P-XANES.xmu.nor", "BSLE_0002-solid_P-XANES.xmu.nor", "BSLE_0050-solid_P-XANES.xmu.nor", "BSLE_0014-solid_P-XANES.xmu.nor", "BSLE_0011-solid_P-XANES.xmu.nor", "BSLE_0072-solid_P-XANES.xmu.nor")

file_paths <- file.path("/Users/barn772/Library/CloudStorage/OneDrive-PNNL/Documents/GitHub/rcsfa-RC3-BSLE_P/Barnes_2024_BSLE_P_Gradient/data/Barnes_2024_BSLE_P_Gradient/P-XANES/P-XANES_Samples", file_names)


merged_data <- file_paths %>%
  lapply(function(file_path) {
    read.table(file_path, header = FALSE) %>%
    select(1:2) %>%  # Keep only the first two columns
    dplyr::rename(eV = V1, sample = V2) # Rename columns
  })


merged_data <- map(file_paths, ~{
  df <- read.table(.x, header = FALSE) %>% 
    select(1:2) %>% setNames(c("eV", basename(.x)))
  })


final_df_samples <- reduce(merged_data, full_join, by = "eV")

#write.csv(final_df_samples, "/Users/barn772/Library/CloudStorage/OneDrive-PNNL/Documents/GitHub/rcsfa-RC3-BSLE_P/Barnes_2024_BSLE_P_Gradient/data/Barnes_2024_BSLE_P_Gradient/P-XANES/P-XANES_Samples/xanes_example_spectra.csv")
```

##Standards
```{r}
#Load standard spectra and merge to make it easier to make a figure

file_names  <- c("Pi_Al_GibbSorb_std.xmu.nor", "Pi_Apatite_CaDefHydroxy_std.xmu.nor", "Pi_Fe_GoethSorb_std.xmu.nor", "Pi_K_Pyro_std.xmu.nor", "Pi_Mg_Tri_std.xmu.nor", "Pi_Na_Tri_std.xmu.nor", "Pi_NH4_Mg_std.xmu.nor", "Po_Ca_Lecithin_std.xmu.nor")

file_paths <- file.path("/Users/barn772/Library/CloudStorage/OneDrive-PNNL/Documents/GitHub/rcsfa-RC3-BSLE_P/Barnes_2024_BSLE_P_Gradient/data/Barnes_2024_BSLE_P_Gradient/P-XANES/P-XANES_Reference_Compounds", file_names)


merged_data <- file_paths %>%
  lapply(function(file_path) {
    read.table(file_path, header = FALSE) %>%
    select(1:2) %>%  # Keep only the first two columns
    dplyr::rename(eV = V1, sample = V2) # Rename columns
  })


merged_data <- map(file_paths, ~{
  df <- read.table(.x, header = FALSE) %>% 
    select(1:2) %>% setNames(c("eV", basename(.x)))
  })

final_df_standards <- reduce(merged_data, full_join, by = "eV") %>%
  mutate_all(~coalesce(., -9999))

#write.csv(final_df_standards, "/Users/barn772/Library/CloudStorage/OneDrive-PNNL/Documents/GitHub/rcsfa-RC3-BSLE_P/Barnes_2024_BSLE_P_Gradient/data/Barnes_2024_BSLE_P_Gradient/P-XANES/P-XANES_Reference_Compounds/xanes_example_referencecompounds.csv", row.names=FALSE)
```

##LCF Examples
```{r}
#Load standard and spectra and merge to make it easier to make a figure
#Example samples = DF: 13, 7, 2, and 50; SB: 14, 11, 72


#Load samples spectra and merge to make it easier to make a figure

file_names  <- c("Pi_Al_GibbSorb_std.xmu.nor", "Pi_Apatite_CaDefHydroxy_std.xmu.nor", "Pi_Apatite_Carbonate_std.xmu.nor", "Pi_Ca_Tri_std.xmu.nor", "Pi_Fe_GoethSorb_std.xmu.nor", "Pi_K_Pyro_std.xmu.nor", "Pi_Mg_Tri_std.xmu.nor", "Pi_Na_Tri_std.xmu.nor", "Pi_NH4_Mg_std.xmu.nor", "Po_Na_AMP_std.xmu.nor")

file_paths <- file.path("/Users/barn772/Library/CloudStorage/OneDrive-PNNL/Documents/GitHub/rcsfa-RC3-BSLE_P/Barnes_2024_BSLE_P_Gradient/data/Barnes_2024_BSLE_P_Gradient/P-XANES/P-XANES_Reference_Compounds", file_names)


merged_data <- file_paths %>%
  lapply(function(file_path) {
    read.table(file_path, header = FALSE) %>%
    select(1:2) %>%  # Keep only the first two columns
    dplyr::rename(eV = V1, sample = V2) # Rename columns
  })


merged_data <- map(file_paths, ~{
  df <- read.table(.x, header = FALSE) %>% 
    select(1:2) %>% setNames(c("eV", basename(.x)))
  })


final_df_lcf <- reduce(merged_data, full_join, by = "eV")
final_df_lcf <- final_df_lcf %>% 
  full_join(final_df_samples)


#write.csv(final_df_lcf, "/Users/barn772/Library/CloudStorage/OneDrive-PNNL/Documents/GitHub/rcsfa-RC3-BSLE_P/Barnes_2024_BSLE_P_Gradient/data/Barnes_2024_BSLE_P_Gradient/P-XANES/P-XANES_Samples/xanes_example_lcf.csv")
```